import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ブログ記事",
  description: "Generated by create next app",
};


// ダミーデータ
const articles = [
  { id: 1, title: "記事1"},
  { id: 2, title: "記事2"},
  { id: 3, title: "記事3"},
]
//　3秒たいき
async function fetchArtcles(){
  await new Promise((resolve)=> setTimeout(resolve,3000))
  return articles;
}
export default async function Blogpage() {
    const articles = await fetchArtcles();
  return (
    <div>
      <ul>
        {articles.map((article)=>(
          <li key={article.id}>title:{article.title}</li>
        ) )}
      </ul>
    </div>
  )
}
